# Generated by Django 4.2.6 on 2023-10-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
