# Generated by Django 4.2.6 on 2023-10-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default='Enter Project end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(default='Enter Project Location', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='Enter Project start date'),
        ),
    ]
