# Generated by Django 4.2.6 on 2023-10-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_project_end_date_alter_project_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(through='manager.MaterialUsage', to='manager.material'),
        ),
    ]
