# Generated by Django 4.2.6 on 2023-10-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_project_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(related_name='materials_used', through='manager.MaterialUsage', to='manager.material'),
        ),
    ]
