# Generated by Django 4.2.6 on 2023-10-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_project_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_assigned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.project')),
            ],
        ),
        migrations.DeleteModel(
            name='MaterialUsage',
        ),
        migrations.AlterField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(related_name='materials_used', through='manager.MaterialAssignment', to='manager.material'),
        ),
    ]
