# Generated by Django 4.2.6 on 2023-10-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_materialassignment_delete_materialusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialassignment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
